### PR TITLE
feat: Add prettyprint class to snippet code blocks

### PR DESCRIPTION
**Pull request by jskeet**
This is a horrible hack, but all alternatives seem worse.

### CODE REVIEW

**Comment by jskeet** [comment]
@tbpg: You'll note the lack of tests at the moment. Any preferences as to how we *should* test this? I'm getting slightly lost trying to read the test code to work out what it's actually testing right now. If we could add something that would generate the "wrong" HTML, then validate that it generates the "right" HTML, that would be ideal - but my guess is that would involve changes to the data in the test bucket at the moment.

Alternatively, I could add a standalone test that just created a temporary directory with some HTML in, ran just the function, then checked the output? (Ideally having both "before-replacement" and "expected after-replacement" as files in testdata?)

**Comment by tbpg** [comment]
Looks good to me. For testing, I don't think we need anything in `testdata` -- can inline strings, create a temp directory, write them to files, run `add_prettyprint`, then check the output.

Something like this (untested):

```python
def test_add_prettyprint():
    tmp_path = pathlib.Path(
        tempfile.TemporaryDirectory(prefix="doc-pipeline.prettyprint.").name
    )

    files = [
        {
            "name": "one.html",
            "input": '<code class="lang-cs">hello</code>',
            "want": '<code class="prettyprint lang-cs">hello</code>',
        },
        {
            "name": "two.html",
            "input": '<code class="prettyprint">hello</code>',
            "want": '<code class="prettyprint">hello</code>',
        },
        {"name": "three.yml", "input": "nothing to do", "want": "nothing to do",},
    ]

    for file in files:
        with open(tmp_path.joinpath(file["name"]), "w") as f:
            f.write(file["input"])
    add_prettyprint(tmp_path)
    for file in files:
        with open(tmp_path.joinpath(file["name"])) as f:
            got = f.read()
            assert got == file["want"]
```

**Comment by jskeet** [comment]
Righto - will give that a whirl now.

**Comment by jskeet** [comment]
(Still working on this - I can't run tests locally which makes things rather trickier.)

**Comment by jskeet** [comment]
@tbpg: Okay, after a few false starts, this should now be okay - PTAL.  (I found that I needed to keep the TemporaryDirectory object so that the directory was still around when writing the files.)

**Review by tbpg — APPROVED** [review]
Thank you!

**Pull request merged**
