### PR TITLE
feat(canonical): add support for nodejs

### PR DESCRIPTION
**Pull request by tbpg**
Note: there is an issue with some Node.js lines being too long for `bufio.Scanner`. So, a followup PR will switch to `bufio.Reader`.

cc @fhinkel

### CODE REVIEW

**Review by dandhlee — APPROVED** [review]
can't read Go that well but generally LGTM.

Just curious, should other languages simply drop in the cloud function URL on `langFunctions` in the future, or is that just for your own usage?

**Review by codyoss — APPROVED** [review]
LGTM

**Review by jskeet — APPROVED** [review]

**Comment by tbpg** [comment]
> Just curious, should other languages simply drop in the cloud function URL on langFunctions in the future, or is that just for your own usage?

Yes, pretty much. Ideally, they'd all use the same query params and we don't need to make it any more complicated than it needs to be.

**Comment by tbpg** [comment]
Thank you for the reviews!

**Pull request merged**
