### PR TITLE
Update version in path for multi-version languages.

### PR DESCRIPTION
**Pull request by dzlier-gcp**

### CODE REVIEW

**Comment by dzlier-gcp** [comment]
Checks passing, ready for review.

**Review by dandhlee — COMMENTED** [review]
Interesting - this is good to know that we haven't been honoring the version info in this part of the pipeline. However, this would actually omit the "latest" version notation for these multi-version languages and we'd subsequently lose that notion on c.g.c. pages as well (I've checked and there doesn't seem to be a way for us to tell which one is "latest" of all versions) as we lazily take the version info and use that unless we see "latest" in the metadata.

**Comment by dzlier-gcp** [comment]
Yeah that occurred to me, I didn't see any way to inform the generator that it was in fact the latest version. However there are redirects on c.g.c that direct versions to /latest if the page isn't there, so they should still land on /latest if there's no direct mapping.

**Comment by dandhlee** [comment]
We never publish to the latest url in the generator, so unless we update the logic somewhere to also update the contents on the /latest, this is going to break quickly :/

**Comment by dzlier-gcp** [comment]
I'm sorry I'm not sure I follow

**Comment by dandhlee** [comment]
Ah oops nevermind, the generator still uses `latest` based on the first version found after sorting. I think we're good.

**Comment by dzlier-gcp** [comment]
Oh were you thinking of library-ref-docs-generator? Yeah 'latest' is definitely used there.

**Review by dandhlee — APPROVED** [review]
Sorry for the confusion! It shouldn't matter how they're stated in the metadata 😓

**Pull request merged**
